### PR TITLE
adds Alex Bilson's site

### PR DESCRIPTION
**Pull request by acbilson**
Thanks for hosting this site!

### CODE REVIEW

**Comment by xdesro** [comment]
Hey @acbilson — looks like some errors in your YAML formatting. If you don't mind cleaning those up I can go ahead and get this merged!

**Comment by acbilson** [comment]
oops, looks like I accidentally truncated the three dashes at the end. Fixed! @xdesro

**Comment by acbilson** [comment]
Screen Shot 2020-12-17 at 11 30 56 AM
My card looks correct in the deploy preview, but I did observe a blank card. Was that already there?

**Comment by xdesro** [comment]
Ooh, that's a fun one. Welp, let's find out!

**Pull request merged**
