### PR TITLE
Create hund.tty1.se.md

### PR DESCRIPTION
**Pull request by Hund**

### CODE REVIEW

**Comment by xdesro** [comment]
Looks good, @Hund — thanks for your contribution!

**Comment by Hund** [comment]
> Looks good, @Hund — thanks for your contribution!

Thanks!

**Comment by Hund** [comment]
Would it be possible to add these tags as well?

* Blog
* Static website
* Plain text

**Comment by xdesro** [comment]
@Hund of course! Feel free to open a new PR with that update!

**Pull request merged**
