### PR TITLE
Update stephenajulu.com.md

### PR DESCRIPTION
**Pull request by stephenajulu**
corrected a spelling mistake, changed and added a few things.

### CODE REVIEW

**Comment by xdesro** [comment]
Hey @stephenajulu — love the site! If it's helpful, `entreprenuer` → `entrepreneur` is another spelling mistake in there. I'll hold off on merging in case you wanna fix this one (happy to merge tho)

**Comment by stephenajulu** [comment]
Thank you, didn't notice the error let me change it

**Comment by stephenajulu** [comment]
Kindly merge, I'll change it later.

**Comment by stephenajulu** [comment]
Thank you

**Pull request merged**
