### PR TITLE
added a site of nabilweq.com

### PR DESCRIPTION
**Pull request by nabilweq**
**What did this PR accomplish?**

- Created a .md file named nabilweq.com.md
- Added site details 

Thank you for your contribution!

### CODE REVIEW

**Comment by nabilweq** [comment]
@xdesro Please accept my PR!

**Comment by nabilweq** [comment]
@jeremyf Please accept my PR!

**Comment by nabilweq** [comment]
@pfefferle Please add `hacktoberfest-accepted` label to this PR

**Comment by xdesro** [comment]
Lol closing not only because the app didn't successfully deploy with your PR but also because you went about this in the most fucken annoying way possible

**Pull request closed without merging**
