### PR TITLE
added ramaiah website

### PR DESCRIPTION
**Pull request by christyram99**

### CODE REVIEW

**Comment by christyram99** [comment]
I added my personal site here. Please check it once.

**Review by xdesro — CHANGES_REQUESTED** [review]
Hey @christyram99 — make sure the file you add is a Markdown file so the site is able to build it. Right now it has a `.com` extension, where most other files in the `sites` directory have a `.md` extension. ( `ramaiahtech.com.md` is totally fine too.) Thanks for your contribution — once you can make this change I'll be happy to merge your PR in.

**Comment by christyram99** [comment]
ok @xdesro , I will make the changes.

**Comment by christyram99** [comment]
Hi @xdesro , I made the changes. Please have look into it.

**Comment by xdesro** [comment]
Nice, thanks for making those changes!

**Pull request merged**
