### PR TITLE
add nerdy.dev

### PR DESCRIPTION
**Pull request by argyleink**
👋🏻

### CODE REVIEW

**Comment by xdesro** [comment]
Hey @argyleink! Thanks for adding your site mate, and thanks for your patience :)

**Comment by argyleink** [comment]
awesome, thanks!

however, the thumbnail on the site appears to have been taken without a stylesheet?

Screenshot 2024-12-11 at 9 52 43 AM

tho it should look like

Screenshot 2024-12-11 at 9 52 30 AM

**Comment by xdesro** [comment]
@argyleink updated! Let me know if there's any issues :)

**Comment by argyleink** [comment]
> @argyleink updated! Let me know if there's any issues :)

thanks for the quick fix! <3

however lol, i'm so sorry…! the card is all faded, as if the page was scrolled a little before taking the picture? https://res.cloudinary.com/personalsites/image/upload/w_600/nerdy.dev.png

**Comment by xdesro** [comment]
Hmm, I tried retaking it but even scrolled all the way up, the cards are faded. It seems like the top card becomes opaque right as it's being scrolled off. FF 132 if that's helpful!

**Comment by argyleink** [comment]
FF 132, like firefox 132?  
i have FF 133, but i dont see any faded cards.  
do you have scroll driven animation experiments (or other related web experiments) turned on in your FF config/flags?

FF133:  
Screenshot 2024-12-12 at 9 22 31 AM

**Comment by xdesro** [comment]
Tried it both with the feature `layout.css.scroll-driven-animations.enabled` toggled on and off — I'll see about making a Firefox update :)

**Comment by argyleink** [comment]
strange you had to go incognito!!
but good call, thanks for workin this out 🙏🏻

**Pull request merged**
