### PR TITLE
Add john.colagioia.net.md

### PR DESCRIPTION
**Pull request by jcolag**
I'd like to be added to the registry, when time permits.

### CODE REVIEW

**Comment by hankchizljaw** [comment]
Howdy, friend, it looks like your site is down?

**Comment by jcolag** [comment]
Strange.  It works for me and <https://www.site24x7.com/check-website-availability.html> can see it from everywhere but Chennai.  Would you happen to be able to see where the connection is breaking?  I'd hate to pass the URL around further (with a new blog) if it's not a transient glitch with the VPS.

**Comment by hankchizljaw** [comment]
I'm based in the U.K and sorry, it's still hanging for me here :(

**Comment by xdesro** [comment]
Seems to be working on my end, so I'll go ahead and merge! Thanks for your contribution, @jcolag!

**Pull request merged**
