### PR TITLE
Add zane.im

### PR DESCRIPTION
**Pull request by zanetaylor**

### CODE REVIEW

**Comment by xdesro** [comment]
Hey @zanetaylor — make sure your file is a `.md` file (most folks do something like `zane.im.md`, otherwise it won't get picked up as a data file by the site generator!

**Comment by zanetaylor** [comment]
Whoops, fixed! Thanks!

**Comment by xdesro** [comment]
@zanetaylor one more try! Looks like this time we're missing correctly formed punctuation on the tags collection.

**Comment by zanetaylor** [comment]
@xdesro Fixed, but it looks like deployment is still failing mysteriously.

**Pull request merged**
