### PR TITLE
Create lucasdidthis

### PR DESCRIPTION
**Pull request by lucasdidthis**
Please add my personal blog to personalsit.es. Thanks!

### CODE REVIEW

**Comment by xdesro** [comment]
Hey @lucasdidthis — looks like you're missing the `.md` file extension on your file! If you don't mind adding that I can get this merged in ASAP!

**Comment by lucasdidthis** [comment]
> Hey @lucasdidthis — looks like you're missing the `.md` file extension on your file! If you don't mind adding that I can get this merged in ASAP!

Thanks for the answer, hope the latest commit did the trick?

**Comment by xdesro** [comment]
That worked perfectly! I adore the microblogged style of this, really nice site! Thanks for the PR!

**Comment by lucasdidthis** [comment]
> That worked perfectly! I adore the microblogged style of this, really nice site! Thanks for the PR!

Thank you very much. I love the idea of https://personalsit.es/ and am happy to be part of it. :-)

**Pull request merged**
