### PR TITLE
Add amxmln.com

### PR DESCRIPTION
**Pull request by amxmln**
Hey there! Discovered this via Mastodon and thought it might be nice to add my site on here as well. 😊 Hope I did everything right with the *.md file. Let me know if I missed something.

First time doing everything through the GitHub web UI, so I sillily made a PR on my own repo at first. 😅 Hope it is still fine.

### CODE REVIEW

**Comment by xdesro** [comment]
Hey @amxmln — thanks for adding your site mate! Looks like the file needs to be renamed to `amxmln.com.md` in order to be picked up by the generator. If you don't mind making that update I can get this merged in ASAP!

**Comment by amxmln** [comment]
Hey @xdesro! Thanks for pointing that out, I completely missed that. 😅  I've renamed the file and synced up my branch with the latest changes on your end.

Thank you for your time!

**Comment by amxmln** [comment]
I’ve just added an RSS feed to my site and updated the entry here accordingly. Am I correct in assuming `updateFeed` refers to the location of the RSS feed? Some sites seem to link to their blogroll instead, so I’m a bit confused. :thinking:

**Comment by xdesro** [comment]
Howdy! `updateFeed` is sorta whatever you want! Feed definitely implies more structure to me, but restricting to only RSS didn't seem particularly useful!

**Pull request merged**
